# Generated by Django 5.1 on 2024-08-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroeconomics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
